[클린코드 리액트 3기 김가은] 장바구니 미션 Step1
next-step/react-shopping-cart pull request #42
Opened 2024-03-31 15:02 UTC by paran22

# Pull Request Template

## 1. 가이드

### 1-1. 배포

### 1-2. 로컬 환경

```bash
# install
yarn

# run
yarn dev
```

## 2. 리뷰 요청 ✍️

### 2-1. 어렵거나 아쉬웠던 점
시간에 쫓겨 구현을 충분히 하지 못한 것 같아서 많이 아쉬워요.
개인적으로 Tailwind class-variance-authority, tailwind-merge 조합해서 사용해보기, storybook + vitest를 사용해보고 싶었는데 우선 이번 미션에서는 사용하지 못했습니다. 다음 미션을 제출할 때는 조금 더 새로운 시도를 해볼게요!

아직 modal이나 snackbar를 추가하지 않아서 장바구니 삭제 시 바로 삭제가 되는 등 ux에서 어색한 부분이 있습니다. 다음 미션진행 시 추가하면서 ux도 더 신경써서 수정해볼게요.

### 2-2. 나누고 싶은 고민
1. dummy data로 개발할 때 낙관적 업데이트
`useDeleteCart.ts` 장바구니에서 상품을 삭제할 때 낙관적 업데이트를 적용해서 먼저 ui를 업데이트 하고, onSuccess에서 invalidateQueris를 해주었어요. 그런데 dummy data를 사용할 때는 실제 db를 업데이트하는게 아니라서, 실제로는 삭제가 일어나지 않는 것 처럼 보입니다(현재는 테스트를 위해 주석 처리를 해두었습니다!) 이렇게 실제 db가 변경되지 않는 경우에 변경이 필요한 api들은 어떻게 테스트할 수 있을까요?
2. 상태관리 라이브러리
어느 시점에 상태관리 라이브러리를 사용해야 할지 어떻게 판단하시나요? 
로그인한 유저 정보와 같이 정말 전역으로 사용이 필요한 상태는 상태관리 라이브러리 도입을 고려해볼 수 있을 것 같은데, 몇몇 컴포넌트에서 props 전달로 해결되는 경우에는 상태관리 라이브러리를 도입해야 하는지 고민을 많이 하는 것 같아요. 이번 미션에서도 장바구니 페이지에서 장바구니 관련 상태들을 여러 컴포넌트들에서 수정하면서 상태관리 라이브러리 도입을 고민했고, 우선은 도입하지 않는 쪽으로 구현하였습니다. 
(도입이 필요할까라는 고민도 있었고, 이후 zustand+test를 해보고 비교해보고 싶어서요!)
상태관리 라이브러리를 사용한다면 props 전달이 줄어들고, 리렌더링도 줄어들텐데 그렇다면 몇몇 컴포넌트에서만 공유되는 상태에서도 항상 상태관리 라이브러리를 사용하는게 좋을까요?

### 2-3. 중점적으로 리뷰받고 싶은 부분
- `CartsPage`(구현하고 보니 해당 부분은 step2에 포함되어 있는데, 피그마만 보고 작업하다보니 일부 기능을 구현하였습니다🙃)
CartsPage에서 처리하는 비즈니스 로직들을 어떻게 분리하는게 좋을지 고민했어요.
우선은 커스텀 훅 `useCarts`와 `useCartsSummary`를 만들었는데, 상태관리 라이브러리를 사용하지 않다보니 데이터를 훅 안에서 접근하지 못하고 매개변수로 전달받아야 하는 문제가 있었습니다. 상태관리 라이브러리를 사용하면 이런 부분은 좀 더 코드가 깔끔해지지 않을까 싶습니다.
- api 폴더
api와 관련된 로직들은 모두 api 안에 포함시켜서 분리해주려고 해봤어요. 이전에 다른 프로젝트를 할 때 useQuery, useMutation이나 api response type들은 각각 공통 `/hooks`, 공통 `/types`에 넣어놨는데, 조금 분산된다는 생각이 들어서요. 이번에는 모두 api 안으로 모아봤는데 어떻게 생각하시는지 궁금합니다!

### 2-4. 새로운 시도 혹은 미션을 통해 도전한 점
- api 폴더 구조 분리
- msw

### 2-5. 도식화된 자료 혹은 작성된 이미지 형태의 설계 구조
<img width="245" alt="스크린샷 2024-04-01 오전 12 01 16" src="https://github.com/next-step/react-shopping-cart/assets/97428216/6e38701f-28de-4b45-abca-bf9d6d52720e">

## 3. 질문있어요 🙋
1. `useCarts` `useCardSummary`를 구현하면서 전체선택은 cart feature에서만 사용하는게 아니라 공통으로 사용할 수 있는 훅으로 분리할 수 있을 거라고 생각했어요. 그런데 현재 구현 요구사항에서는 아직 (전체)선택 기능이 cart외에는 없습니다. 이런 경우에는 아직 cart에서만 사용하는 로직이지만 이후 변경 가능성?을 고려해서 분리하는게 좋을까요? 아니면 나중에 선택 기능이 생기면 그 때 분리를 하는게 좋을까요???  
프론트 구현을 하다보면 자주 반복되는 기능들이 있는데, 이런 기능들을 만날 때마다 현재 여기서만 쓰이는데 분리를 하는게 좋을지 고민을 합니다. 어떻게 생각하시나요???
2. type 관리
api와 관련된 모든 로직, 타입들을 `/api`로 분리해두었어요. 그리고 장바구니 기능을 구현하면서 api repsonse와는 상관없는 `/types/Cart.ts`라는 타입을 정의했습니다. 그런데 이렇게 만들고 나니 타입이 분산되는게 아닌가 하는 고민이 생겼습니다. api response/request 타입들을 /api 바깥으로 빼서 다른 타입들과 같이 관리하는게 좋을까요?
3. 폴더구조
형식(types, hooks, components ...)을 우선으로 나눌지, feature(product, cart ...)를 우선으로 나눌지 프로젝트마다 고민하게 됩니다. 폴더 구조를 나눌 때 어떤 걸 고려하시나요??
 
## 4. 요구 사항 ✅ Step1-2

### 4-1. 필수 요구사항

- [x] TanStack Query를 기반으로 상태 분리
  - [x] 낙관적 업데이트를 활용하여 UX/UI 증진
- [x] MSW를 활용한 API mocking
- [x] Endpoint만 변경하면 언제든 Real API를 바라볼 수 있다고 가정하고 상상한다.
  - [x] Real API 없이 로컬에서만 동작하는 상태로 리뷰 받는 것이 기본 원칙
- [ ] 상태 관리 라이브러리가 필요하다면 추가적으로 선택하고 적용한다.
  - [ ] 전략을 세우고 PR 본문에 내용을 작성한다.

#### GNB

- [x] 로고를 누르면 상품목록 페이지로 이동한다.
- [x] 장바구니 버튼을 누르면 장바구니 페이지로 이동한다.
- [x] 주문목록 버튼을 누르면 주문목록 페이지로 이동한다.

#### 상품목록

- [x] 상품들은 n x 4 레이아웃으로 보여진다.
- [x] 상품들에는 사진, 이름, 금액이 보여진다.
- [ ] 장바구니 버튼을 클릭하면 (\*\*) / 자유롭게 구현 후 내용 작성
- [ ] 페이징 혹은 인피니티 스크롤 적용
  - [ ] 뒤로가기 및 페이지 전환시 기존 페이지 및 스크롤 위치 기억

#### 장바구니

- [x] 해당 상품의 수량을 변경할 수 있다.
  - [x] 상품의 수량은 항상 1이상, 20이하여야 한다
    - [x] 상품의 수량이 1이면 상품 수량 감소할 수 없다.
    - [x] 상품의 수량이 20이면 상품 수량 증가할 수 없다.
  - [x] 해당 상품의 총 금액이 변경된다.
  - [x] 해당 상품이 체크되어있으면, 결제예상금액도 변경된다.
- [x] 모두선택 버튼이 체크되면, 상품들이 모두 선택된다.
  - [x] 모두선택 버튼이 체크가 풀리면, 상품들의 선택이 모두 해제된다.
- [ ] 상품 삭제 버튼을 누르면, confirm 메시지가 보여진다.
  - [ ] 확인을 누르면, 선택된 상품이 모두 삭제된다.
  - [ ] 결제예상금액이 0원이 된다.
- [ ] 🗑 버튼을 누르면 confirm 메시지가 보여진다.
  - [x] 확인을 누르면, 해당 상품이 삭제된다.
- [x] 체크된 상품 개수에 따라 주문하기 버튼 내부에 수량이 변경된다.
- [ ] 주문하기 버튼을 누르면, confirm 메시지가 보여진다.
  - [ ] 확인을 누르면, 주문/결제 페이지로 이동한다.
  - [ ] 확인을 누르면, 장바구니에서 선택된 상품들이 삭제된다.
  - [ ] 확인을 누르면, 체크된 상품들을 데이터베이스에서 제거한다.
- [ ] 주문할 상품이 0개이면 버튼이 비활성화된다.

### 4-2. 선택 요구사항 (심화)

#### 상품 상세

- [ ] 페이지에는 상품 사진, 이름, 금액 정보가 보여진다.
- [ ] 장바구니 버튼을 클릭하면 장바구니 페이지로 이동한다.
- [ ] 장바구니 버튼을 클릭하면 해당 상품이 장바구니에 담긴다.

#### 주문 상세

- [ ] 주문 정보가 보여진다.
- [ ] 장바구니 버튼을 클릭하면, 해당 상품이 장바구니에 담기고 장바구니 이동 선택 모달이 보여진다.
- [ ] 장바구니 이동 버튼을 누르면 장바구니 페이지로 이동한다.

#### UX/UI
- [ ] 반응형 레이아웃을 구현한다.
- [ ] 사용성 개선
  - [ ] 사용자를 위한 로딩 환경 개선
  - [ ] 상품이 없을 때와 같은 다양한 Edge Case 대응
  - [ ] 반응형 레이아웃 구현
  - [ ] 별도의 모바일 레이아웃 추가 제공
- [ ] 매출 증대 및 마케팅을 위해 별도의 기능 구현 (별도의 API 없음)
  - [ ] 브라우저 새로고침시 모든 상태 유지
  - [ ] 흐름을 고려한 맞춤 큐레이팅 상품 추천 기능
  - [ ] 구매 유도를 위한 상품 찜 페이지
- [ ] 매출 증대 및 마케팅을 위한 별도의 도구 추가
  - [ ] Google Analytics
  - [ ] Google Tag Manager

2024-04-02 14:21 UTC, igy95 requested changes
안녕하세요 가은님~ 1단계 미션 고생 많으셨습니다. 코멘트 남겨두었으니 확인 부탁드리고 질문에 대한 답변으로 마무리할게요!

#### dummy data로 개발할 때 낙관적 업데이트

> 이렇게 실제 db가 변경되지 않는 경우에 변경이 필요한 api들은 어떻게 테스트할 수 있을까요?

이러한 케이스가 왜 필요한 건지가 먼저 궁금합니다. db를 건드리지 않으면서 api 동작 테스트를 하기 위해서는 api mocking을 해서 네트워크 호출을 했다고 가정하고 테스트를 진행하지 않나요? 말씀하신 dummyData의 역할이 무엇인지 잘 와닿지 않네요!

#### 상태관리 라이브러리

내부의 문제를 먼저 정의하고 -> 이것을 해결할 방법을 찾는 식으로 접근해보면 좋을 것 같습니다. 즉, 현재의 어려움이 없고 (혹은 있지만 판단이 서지 않고) 왠지 써야할 것 같아서 쓰는 거라면 오히려 억지스러운 구조를 만들어내기 쉬워질 것 같아요.

tanstack-query를 사용하면서 대부분의 비동기 상태들이 관리되고 있기 때문에 클라이언트 단에서 자체적으로 관리할 상태는 없어보이는 것이 정상이라고 생각합니다. 따라서 웬만한 상태 관리는 Context api로 사용 가능하다면 사용하면서 특정 라이브러리만 제공하는 이점이 있고 그걸 써보고 싶을 때 쓰는 게 좋지 않을까 싶습니다.

#### api 폴더

각 레이어 간 누가 누굴 알아야 하는지를 먼저 정의해보면 좋을 듯 합니다. 현재는 `api` 레이어에서 넓은 관심사를 다루고 있는 것으로 보이네요..!

> 프론트 구현을 하다보면 자주 반복되는 기능들이 있는데, 이런 기능들을 만날 때마다 현재 여기서만 쓰이는데 분리를 하는게 좋을지 고민을 합니다. 어떻게 생각하시나요???

때에 따라 다르다고 생각하지만, 웬만하면 코드 작성 시점에 분리까지 진행해놓는 것이 추후 본인이나 다른 작업자를 위해 더 바람직한 방향이 아닐까 싶습니다!

> 그런데 이렇게 만들고 나니 타입이 분산되는게 아닌가 하는 고민이 생겼습니다. api response/request 타입들을 /api 바깥으로 빼서 다른 타입들과 같이 관리하는게 좋을까요?

고민의 방향이 무엇인지 잘 모르겠습니다. 가은님이 현재 구조에서 생각하시는 장단점은 무엇인가요?

> 폴더 구조를 나눌 때 어떤 걸 고려하시나요??

frontend folder structure, frontend architecture, feature based folder structure 등으로 찾아보시면 좋을 것 같습니다!

> 컴포넌트 이름에 구체적인 ui가 들어가는게 좋을까요?? 예를 들어 -Button, -Table, -List 이런 식으로요. 이렇게 붙이면 어떤 컴포넌트인지 빨리 알 수 있다는 장점이 있는 것 같고, 반면에 ui가 변경되면 컴포넌트 이름 수정도 함께 해야한다는 점이 단점 같습니다.

구체적인 네이밍이 들어가있기 때문에 ui 수정시 네이밍도 수정이 필요하다는 사실을 인지할 수 있지 않을까요? 그리고 UI가 바뀌면, 내부 로직도 바뀔 가능성이 크기 때문에 아예 새로운 컴포넌트를 만들지 않을까 싶습니다.

> 자주 업데이트되는 데이터인지 외에 고려할 수 있는 점이 있을까요?

제 생각은 아래와 같습니다.

1. 웬만하면 현재 시점에서 가장 최신의 데이터를 사용자에게 보여주는 것이 좋음
2. 1번을 충족할 수 없는 경우 (e.g. 데이터를 가져올 때마다 부하가 많이 든다거나, 데이터를 가져오는 지점이 멀어서 응답 시간이 오래 걸리는 경우) 적절한 캐싱 전략을 고려

결국 데이터의 신선도와 쾌적한 ux 사이에서 트레이드 오프를 고려해야겠죠!

2024-04-02 14:21 UTC, igy95 commented on index.html
> +    <title>Vite + React + TS</title>
title을 바꿔주어야 하지 않을까요~?

2024-04-02 14:21 UTC, igy95 commented on src/types/Cart.ts
`CartModel`과 `Cart`의 차이가 무엇인가요?

2024-04-02 14:21 UTC, igy95 commented on src/api/axios/cartApi.ts
> +export const getCarts = async (): Promise<ApiResponse<CartModel[]>> => {
`axios`에서 제공하는 response type이 있지 않을까요?

2024-04-02 14:21 UTC, igy95 commented on src/api/hooks/index.ts
hook 레이어가 api 하위에 있는 이유를 알 수 있을까요? 위계로 따져보면, hook에서 api를 사용하는 게 아닌가 싶어서요!

2024-04-02 14:21 UTC, igy95 commented on src/api/index.ts
하나의 모듈 안에서 이렇게 넓은 범위를 re-export 했을 때 고려해볼 수 있는 단점은 없을까요?

2024-04-02 14:21 UTC, igy95 commented on src/components/layout/Logo.tsx
> +      <Button>
시맨틱 관점으로 보았을 때 `Link` 안에 `Button`이 들어있어도 되는 걸까요~?

2024-04-02 14:21 UTC, igy95 commented on src/components/layout/PageTitle.tsx
> +const PageTitle = React.memo(({ title }: PageTitleProps) => {
여기는 `memo`로 감싸주신 의도가 있으실까요?

2024-04-02 14:21 UTC, igy95 commented on src/pages/products/components/Products.tsx
> +  data: ProductModel[];
props 이름으로 `data`는 꽤 포괄적으로 느껴지네요..! 좀 더 구체적으로 네이밍을 주면 어떨까 싶어요

2024-04-02 14:21 UTC, igy95 commented on src/pages/orders/OrdersPage.tsx
> +      {orders &&
`useQuery`의 특성 상 `data`가 `T | undefined`로 판별되어 사용하는 쪽에서 nullable 체크를 매번 해줘야 할 듯 한데, 이러한 귀찮음을 query 단에서 해결해볼 수는 없을까요?

2024-04-02 14:21 UTC, igy95 commented on src/pages/carts/hooks/useCartsSummary.ts
> +export default function useCartsSummary(carts: Cart[]) {
내부에서 react 상태를 다루는 게 없어 보이는데 단순 유틸 함수로 빼도 되지 않을까요?

2024-04-02 14:21 UTC, GwangYeol-Im commented on src/pages/carts/components/CartsAllSelector.tsx
> +  selectAll: () => void;
props 명이 좀 헷갈리는 듯 한데, boolean flag 변수는 `is-*` prefix를 붙여주면 어떨까요?

2024-04-02 14:21 UTC, GwangYeol-Im commented on src/api/hooks/useGetProducts.ts
> +    staleTime: 1000 * 60 * 4,
`staleTime` 설정 기준은 어떻게 되나요?

2024-04-04 12:21 UTC, paran22 commented on src/types/Cart.ts
api response type과 실제 컴포넌트에서 사용하는 type이 차이가 있어서 구분했어요. 현재 이름으로는 구분이 잘 안되는 것 같아서 api response type들은 `-Response` 로 수정하였습니다!

2024-04-04 12:47 UTC, paran22 commented on src/api/axios/cartApi.ts
> +export const getCarts = async (): Promise<ApiResponse<CartModel[]>> => {
`db.json`에 있는 데이터들을 모두 data로 한번 wrapping해서 response 하고 있어서 별도로 타입을 만들었습니다!
```
http.get('/products', () => {
  return HttpResponse.json({
    data: mockDb.products,
  });
})

// response 예시
{
  "data" : [
       {
          "id": 1,
          "name": "냉면용기(대)",
          "price": 83700,
          "imageUrl": "https://cdn-mart.baemin.com/goods/2/1556008840639m0.jpg"
       },
    ]
}
```

2024-04-04 12:53 UTC, paran22 commented on src/api/hooks/index.ts
네 맞습니다😂 
Tanstack Query hook들을 어디에 위치시킬지 고민하다가 `/api`에 포함을 시켰는데, 코멘트 주신걸 보고 생각해보니 hook쪽으로 분리하는게 더 적절할 것 같네요!

2024-04-04 13:13 UTC, paran22 commented on src/api/index.ts
`/api` 하위의 모든 파일들이 폴더 구분없이 export되서, import가 너무 구분 없이 모두 `@api`라고 느껴질 수 있을 것 같아요.
저는 api에서 export 된다는 것만 명시해도 충분하다고 생각했는데, `@api/types`, `@api/axios` 정도로 묶어서 export 하는게 좀 더 가독성이 좋을까요?

```
import { type CartResponse, deleteCart, type ApiResponse } from '@api';
```

2024-04-04 13:48 UTC, paran22 commented on src/components/layout/PageTitle.tsx
> +const PageTitle = React.memo(({ title }: PageTitleProps) => {
PageTitle은 한 페이지 내에서는 한번 렌더링된 이후에는 변경되지 않아서, 불필요한 렌더링을 막고자 React.memo를 사용했습니다!

2024-04-04 14:04 UTC, paran22 commented on src/pages/products/components/Products.tsx
> +  data: ProductModel[];
최근에 컴포넌트 props 네이밍에 대해 고민을 하고 있어요. props 이름을 너무 구체적으로 사용하는 것보다 비슷한 성격의 props들은 동일한 이름을 사용하는게 조금 더 가독성이 좋은 것 같고, 또 수정에도 유연하게 대처할 수 있을 것 같아서 모두 `data`라고 이름지었습니다. 해당 컴포넌트에 필요한 데이터를 전달한다는 의미로요!

그런데 오히려 너무 추상화해서 가독성이 떨어진다고 느껴질 수도 있을 것 같네요😭 이부분은 고민을 조금 더 해보겠습니다!

2024-04-04 14:08 UTC, paran22 commented on src/pages/orders/OrdersPage.tsx
> +      {orders &&
data가 아직 loading되기 전에는 undefined이기 때문에, 로딩되고 나서 화면을 그려주려는 목적으로 이렇게 사용했어요.
코멘트를 보고 생각해보니 loading을 체크하려고 한다면 `isLoading`이나 `status`로 체크하는게 더 적절한 것 같네요.

2024-04-04 14:19 UTC, paran22 commented on src/api/hooks/useGetProducts.ts
> +    staleTime: 1000 * 60 * 4,
상품 데이터는 자주 업데이트해주지 않아도 될 것 같아서 staleTime을 늘렸고, cacheTime default가 5분이라는 점을 고려해서 4분으로 설정했습니다. 

그런데 위에 코멘트 남겨주신걸 보고 생각해봤을 때, 상품 데이터는 페이지네이션까지 고려하면 무겁지 않은 api라서 굳이 staleTime을 늘리지 않고 default로 사용해도 되지 않을까 고민되네요 🤔

2024-04-04 14:35 UTC, paran22 commented
> Q. dummy data로 개발할 때 낙관적 업데이트
이렇게 실제 db가 변경되지 않는 경우에 변경이 필요한 api들은 어떻게 테스트할 수 있을까요?
A. 이러한 케이스가 왜 필요한 건지가 먼저 궁금합니다. db를 건드리지 않으면서 api 동작 테스트를 하기 위해서는 api mocking을 해서 네트워크 호출을 했다고 가정하고 테스트를 진행하지 않나요? 말씀하신 dummyData의 역할이 무엇인지 잘 와닿지 않네요!

```
  const { mutate } = useMutation({
    mutationFn: deleteCart,
    onMutate: async (cartId: number) => {
    ...
      // 낙관적 업데이트 : api call 성공이 반환되기 전에 삭제가 적용된 데이터로 set
      queryClient.setQueryData<ApiResponse<CartResponse[]>>([CARTS_QUERY_KEY], {
        data: newCarts,
      });
    ...
    },
    onSuccess: () => {
      // api call이 성공하면 invalidateQueries를 통해 서버에서 carts를 새로 호출
      // 그러나 dummy data를 사용하면 실제로 데이터가 삭제된 것이 아니기 때문에, 카트 삭제 전 데이터가 호출됨.
      // queryClient.invalidateQueries({ queryKey: [CARTS_QUERY_KEY] });
    },
  });
```

제가 낙관적 업데이트를 구현한 부분이에요!
Cart 삭제를 할 때 api call response를 기다리지 않고,
1. 먼저 Cart 삭제가 반영된 상태로 set을 해주고,
2. api call이 성공하면 invalidateQueries를 통해 서버에서 carts 정보를 새로 호출하도록 구현했습니다.

그런데 현재 프로젝트는 아직 백엔드 api가 아니라 msw를 통해 `db.json`을 반환하도록 하고 있어요.
그래서 삭제 후 2번을 통해 Carts를 새로 불러와도 항상 `db.json`에 있는 데이터를 가져오기 때문에 삭제가 반영되지 않습니다.
이런 경우에 어떻게 테스트를 할 수 있을까, 에 대한 질문이었습니다!
(현재는 storybook이나 테스트코드가 없이 브라우저에서만 테스트하고 있어요!)

2024-04-07 11:51 UTC, GwangYeol-Im commented on src/api/index.ts
가독성 측면 뿐만 아니라, 빌드 시 번들 사이즈에 가해지는 영향 측면에서 고려해보면 좋을 것 같습니다. tree shaking이라는 키워드로 찾아보시면 좋겠네요!

2024-04-07 11:57 UTC, GwangYeol-Im commented on src/pages/products/components/Products.tsx
> +  data: ProductModel[];
넵 현재는 하나의 컴포넌트당 담당하는 데이터가 하나라 그렇게 느껴질 수 있겠지만, 어떠한 컴포넌트를 아무리 역할에 맞게 쪼개어도 구조 상 두 개 이상의 데이터를 props로 넣어야 하는 경우도 한번 고려해보면 어떨까 싶어요!

개인적인 의견으로는 컴포넌트의 이름은 ui-like 하게 만든 뒤(e.g. `ProductList`), 데이터를 실제 역할에 맞는 이름으로 치환하여 사용하는 것이 제일 명확하게 읽힐 듯 싶습니다.

2024-04-07 11:59 UTC, GwangYeol-Im commented on src/pages/orders/OrdersPage.tsx
> +      {orders &&
데이터의 nullable이나 `isLoading`과 같은 상태 변수나 매 컴포넌트마다 일일이 대응해줘야 한다는 점은 변함 없을 것 같아요. 현재 tanstack query v5 버전을 사용하고 계시니, `useSuspenseQuery` api 문서를 살펴보시면 좋을 듯 합니다~

2024-04-07 12:03 UTC, GwangYeol-Im commented on src/api/hooks/useGetProducts.ts
> +    staleTime: 1000 * 60 * 4,
> 상품 데이터는 자주 업데이트해주지 않아도 될 것 같아서

실제 커머스 앱을 생각하면, 공급자가 상품의 정보를 바꿨는데 (e.g. 가격, 할인율, 품절 여부) 사용자 측에서 이러한 정보가 바로 반영되지 않아 이전 정보로 주문이 성사되면 큰 문제이지 않을까요? 데이터 캐싱 여부는 이 앱의 실제 사용자 입장과 데이터를 관리하는 서버의 성능을 전반적으로 고려하여 결정하는 것이 바람직해 보이네요!

2024-04-07 12:17 UTC, GwangYeol-Im approved these changes
안녕하세요 가은님~ 세부 코멘트 추가로 달아두었으니 확인 부탁드리며 커뮤니케이션 측면의 피드백 하나와 질문에 대한 답변 남기고 마무리하겠습니다! 😀

#### 커뮤니케이션 측면의 피드백

PR에 달린 리뷰 코멘트의 resolve 여부는 리뷰어 쪽에서 확인 후 처리하는 것이 맞을 듯 합니다. 대개 '모든 코멘트가 resolve 되었다' -> '이 PR은 approve 가능하다'의 용도로 사용되는 기능이기 때문이에요. 2차 리뷰를 하러 들어왔을 때 몇몇 코멘트가 이미 resolve 처리되어 있어 하나하나 다시 확인하게 되어 코멘트 남겨두었습니다 :)

#### 낙관적 업데이트

msw를 사용하여 api의 동작과 '똑같이' 확인되길 원한다면, msw에서 반환하는 값을 백엔드의 로직과 동일하게 처리하여 만들어줘야 하지 않을까요? 하지만 모킹 테스트 자체가 실제 구현 방식과 유사하게 만들 수는 있지만 실제 동작과 아예 똑같이 만들기엔 기능적 한계 or 투입하는 리소스 문제도 고려해야하기 때문에 저라면 '이 동작만 검증이 되면, 그 후의 동작은 문제없이 동작하겠구나'하는 지점을 정해두고 프론트엔드에서 검증이 필요하고 검증 가능한 부분만 처리해둘 것 같습니다.

2024-04-07 12:19 UTC, merged

2024-04-07 13:31 UTC, paran22 commented
답변 감사합니다!! 코멘트 주신 내용 참고해서 다음에는 더 좋은 코드로 리뷰 요청하겠습니다!😌