Features/step 01
next-step/react-shopping-cart pull request #9
Opened 2023-03-19 19:17 UTC by sooooo-an

# Pull Request Template

## 1. 가이드

### 1-1. 배포

> 배포된 페이지가 있다면 링크를 남겨주세요 (삭제)

- [LMS](https://edu.nextstep.camp)
- [CSS](next-step.github.io/shopping-cart-css)

### 1-2. 로컬 환경

> 로컬 환경 확인이 필요하다면 예시와 같이 남겨주세요 (삭제)

```bash
# install
yarn

# run
yarn dev

# test
yarn test
```

## 2. 리뷰 요청 ✍️

### 2-1. 어렵거나 아쉬웠던 점

### 2-2. 나누고 싶은 고민

### 2-3. 중점적으로 리뷰받고 싶은 부분

### 2-4. 새로운 시도 혹은 미션을 통해 도전한 점

### 2-5. 도식화된 자료 혹은 작성된 이미지 형태의 설계 구조

## 3. 질문있어요 🙋

## 4. 요구 사항 ✅

> 예시를 참고하여 체크 박스를 활용해주세요 (삭제)

### 4-1. 필수 요구사항

- [ ] `Storybook` 상호 작용 테스트
- [ ] `MSW`를 활용한 `API mocking`

### 4-2. 선택 요구사항 (심화)

- [ ] 반응형 레이아웃을 구현한다.

2023-03-21 16:19 UTC, yujo11 requested changes
안녕하세요 수경님~

만나서 반갑습니다~

배포까지 진행 해주셨는데 아쉽게도 배포 된 페이지가 아래처럼 현재 동작하지 않네요 ㅠㅠ

<img width="520" alt="image" src="https://user-images.githubusercontent.com/61097373/226668873-2533bc58-feee-4efd-91b3-2a6d600635ad.png">

Storybook은 정상적으로 확인할 수 있어서 리뷰하는데 도움이 됐습니다 🙇‍♂️🙇‍♂️

LMS, CSS라는 이름이 조금 모호하게 느껴져서 처음에 보고 어떤 링크에 무엇이 들어이쓴지 예측하기 힘들었는데요. "웹사이트"나 "스토리북 링크"처럼 조금 더 명확한 이름을 사용해주셔도 좋을거 같네용ㅎㅎ

>useEffect가 각 페이지마다 중복되고 있는데, 중복을 제거할 수 있을 거 같은데, 스탭2에서는 라이브러리를 사용할 수 있을 수 있어서 굳이 hooks로 뺼 필요가 없을 거 같아서 그냥 넣어놨습니다 ㅜㅜ

코멘트로 남기려다가 요 멘트를 보고 남기지 않았는데요 ~ 

말씀하신대로 다음 step에서 해결될 부분이지만 현재 코드를 볼 때는 조금 아쉬웠네요

>아쉬운점은 tailwindcss를 사용하면, 컴포넌트에 스타일과 컴포넌트가 한 파일에 있어 가독성이 떨어지는 거 같아서 사알짝 아쉬운 감이 있습니다 ㅠ

저는 tailwind에 익숙해서 그런지 오히려 스타일과 HTML Tag들을 한번에 볼 수 있어서 편했습니다 ㅎㅎ

>스토리북을 최대한 열심히 짜려고 하고 있는데, product 컴포넌트 같은 product 데이터를 전체적으로 내려주는 컴포넌트에서도 스토리북이 효율적인지가 조콤 궁금합니다. 현재 저희 회사에서는 디자인시스템 한정으로 사용하고 있다보니, 어디에서나 사용되면서, 디자이너와 협업이 필요한 곳에서만 스토리북을 쓰고 있고, 각 기능별로 만들어지는 컴포넌트에서는 사용하고 있지 않아서용..! 다른 회사에서는 어떻게 하고 있는지 궁금해요

저도 회사에서 수경님이 말씀해주시는 용도 정도로만 사용하고 있는거 같아요. 디자인 QA를 진행할 때도 storybook이 아닌 실제로 구현된 페이지를 보고 진행하구요.

조금 오래 된 영상이지만 [이 영상](https://www.youtube.com/watch?v=jc9xKzdkYDg)을 한번 보시는 것도 도움이 될거 같네요!

>폴더구조를 어떻게 짜야 더 효율적인지 매번 고민을 하는데, 확장을 하게되면 폴더구조가 효율적이지 않게 되는 경우가 있어서 조콤 이 부분이 궁금합니다

저는 선언하는 곳과 사용하는 곳이 가까이 있는걸 선호하는데요. 예를 들어 특정 페이지에서 사용되는 컴포넌트는 해당 페이지의 근처에 선언하는 식인데요.

간단한 예시로 아래 구조에서 A보다는 B의 형태로 밀집도 있게 코드를 작성하는 게 나중에 유지보수 할 때도 더 편하더라구요~

이게 정답이다! 라는건 아니고 저는 이렇게 한다이니 참고만 부탁드리겠습니다!

- A
```
.
└── src
    ├── api
    │   └── v1
    │       └── warehouse
    │           ├── warehouse-list.ts
    │           └── warehouse.ts
    ├── components
    │   └── vendor
    │       └── warehouse-list
    │           └── SearchPanel
    │               ├── SearchPanel.tsx
    │               ├── index.ts
    │               └── style.tsx
    ├── containers
    │   └── vendor
    │       └── VendorListContainer
    │           ├── VendorListContainer.tsx
    │           └── index.ts
    └── types
        └── dtos
            └── warehouse
                └── warehouse-list.ts
```
- B
```
.
└── src
    └── domain
        └── vendor
            └── warehouse-list
                ├── api
                │   └── warehouse-list.api.ts
                ├── components
                │   └── SearchPanel
                │       ├── SearchPanel.tsx
                │       ├── SearchPanle.styled.tsx
                │       └── index.ts
                ├── page
                │   └── WarehouseListPage
```

>hook을 이용하여 path 상수를 내려보내주면 이동시켜주는 함수를 하나 만들까했는데, 굳이 만들필요가 있을까 싶어서 안만들었어요.,.. useNavigate로도 충분할 거 같아서,,,?

저도 굳이 필요없겠다는 생각이 드네요

>흐름을 고려한 맞춤 큐레이팅 상품 추천 기능 <- 힌트.. 주실 수 있나요? 어떤 흐름을 고려하는 건지 모르겠어요.. ㅠ
>별도의 모바일 레이아웃 추가 제공 <- m.url.com/products 이런 것처럼 m 페이지를 따로 만들라는 뜻인지 궁금합니당

미션 요구사항에 대한 부분은 저보다는 현석님이나 동준님에게 #cc-rc-2기 채널을 통해서 질문 하시는게 더 정확할거 같네요

---

필수 요구사항 외에도 선택 요구사항들까지 구현하시는 게 쉽지 않으셨을텐데 멋지네요 👍 

추가로 구현하려고 하셨던 부분들은 다음 리뷰 요청 주시기 전에 추가해서 같이 리뷰 요청 주시면 좋을거 같네
요!

2023-03-21 16:19 UTC, yujo11 commented on src/App.css
이 파일이나

2023-03-21 16:19 UTC, yujo11 commented on public/robots.txt
이 파일

2023-03-21 16:19 UTC, yujo11 commented on public/mockServiceWorker.js
이 파일처럼 사용되지 않는 파일들은 삭제해주시면 File Tree를 탐색하기도 좋고, PR 시 file changed에서도 보기가 더 좋을거 같네용~

2023-03-21 16:19 UTC, yujo11 commented on src/api/cartHttpClient.ts
> +  return axios.get('/api/carts').then((res) => res.data)
API 요청 시 `res.data`를 반환하는 로직이 반복되고 있는데요. 

이런 반복되는 로직은 공통 로직으로 분리해보셔도 좋을거 같아요!

`axios.interceptors`에 대해 찾아보셔도 좋을거 같네요!

2023-03-21 16:19 UTC, yujo11 commented on src/api/cartHttpClient.ts
> +const addCart: AddCartFn = async (cartItem: CartItemType) => {
함수의 시그니쳐를 위에서 선언해서 사용하고 있는데 `cartItem`에 타입 지정을 다시 해주신 이유가 있으실까용?

2023-03-21 16:19 UTC, yujo11 commented on src/api/ordersHttpClient.ts
> +const addOrder: AddOrderFn = async (order: OrderProductsType) => {
여기도 위에 남긴 것처럼 다시 타입을 지정해주지 않아도 타입 추론이 될거 같네용

2023-03-21 16:19 UTC, yujo11 commented on src/App.tsx
처음 `App.tsx` 파일을 열어보고 조금 당황했는데요

`RouterProvider`는 `index.tsx`에 있고 나머지는 `App.tsx`에 있는 이유가 있을까요?

2023-03-21 16:19 UTC, yujo11 commented on src/utils/routers.tsx
> +    errorElement: <NotFound />,
errorElement에 대한 처리도 해주셨군요 👍 👍

2023-03-21 16:19 UTC, yujo11 commented on src/utils/routers.tsx
> +export const router = createBrowserRouter([
`createbrowserrouter`가 뭔가 했더니 v6에서 추가된 권장되는 사용방법이군요 하나 배워갑니다 🙇‍♂️

2023-03-21 16:19 UTC, yujo11 commented on src/utils/formatter.ts
> +export const convertCurrencyFormet = (num: number) => {
오타가 난거 같네요

2023-03-21 16:19 UTC, yujo11 commented on src/utils/formatter.ts
> +}
그리고 이게 별도의 util로 분리할만한 함수일까 하는 생각이 드네요

오히려 필요한 곳에서 직접 `toLocaleString('ko')`를 호출해서 사용하는게 코드를 보기 더 좋을거 같아서요!

2023-03-21 16:19 UTC, yujo11 commented on src/mocks/carts.ts
> +    const currentCartItem = { ...cartItem, id: CARTS.length + 1 }
지금은 아이템을 생성하는 기능이 없는거 같지만 `id`를 length + 1로 주게 되면 아래와 같은 케이스가 생길 수 있을거 같아요

```
// 초기
cartItmes: [ ]

// "foo", "bar" 생성
cartItmes: [  { id: 1, name: "foo" } ,{ id: 2, name: "bar", }]

// "foo" 삭제
cartItmes: [  { id: 2, name: "bar", } ]

// "baz" 생성
cartItmes: [  { id: 2, name: "bar" }, { id: 2, name: "baz" } ]
```

2023-03-21 16:19 UTC, yujo11 commented on src/pages/Cart.tsx
> +  if (loading) return <div>...loading</div>
오 loading 상태까지 직접 구현하셨군요! 멋집니다! 👍 👍 👍

2023-03-21 16:19 UTC, yujo11 commented on src/pages/Cart.tsx
> +  const [error, setError] = useState(null)
그런데 이 `error`라는 status는 set 하는 부분은 보이지만 사용하는 곳이 어디인지 잘 모르겠네용

2023-03-21 16:19 UTC, yujo11 commented on src/pages/Cart.tsx
> +  const [carts, setCarts] = useState<CartItemType[] | []>([])
빈 배열은 어떠한 요소도 포함하지 않은 배열이고, `CartItemType[]`은 배열의 모든 요소가 `CartItemType`이어야 한다는 제약인데요.

그렇기 때문에 아래와 같이 타입을 지정해주셔도 됩니다!
```suggestion
  const [carts, setCarts] = useState<CartItemType[]>([])
```

2023-03-21 16:19 UTC, yujo11 commented on src/pages/Cart.tsx
> +  const [error, setError] = useState(null)
`loading`의 경우 처음에 boolean 값인 `false`를 할당해서 boolean으로 추론되고, 이후 boolean 값을 할당할 수 있는데요.

반면 `error`의 경우 처음에 `null`로 할당했기 때문에 아래처럼 할당하면 에러가 발생할거에요.

```ts
setError(SomeErrorObject)
```

에러에 대한 타입을 지정해주시면 좋을거 같네요!

2023-03-21 16:19 UTC, yujo11 commented on src/pages/Cart.tsx
> +              </ul>
태그를 시맨틱하게 사용하셨군요 👍 👍

2023-03-21 16:19 UTC, yujo11 commented on src/pages/Orders.tsx
> +                <OrderProducts key={order.id} order={order} />
위에서 본 `CartItem`는 `<li>`로 사용하는 곳에서 감싸주는데 `OrderProducts`는 컴포넌트에서 `<li>`로 감싸서 반환해주네요.

혹시 이렇게 작성하신 이유가 있으실까요?

2023-03-21 16:19 UTC, yujo11 commented on src/pages/ProductDetail.tsx
> +  useEffect(() => {
개행도 코딩 컨벤션에 포함이 된다고 생각하는데요.

적절하게 개행을 섞어주시면 코드를 보기가 훨씬 편할거 같아요!

2023-03-21 16:19 UTC, yujo11 commented on src/pages/ProductDetail.tsx
> +      ?.getProduct(productId ?? '')
`productId`가 없다면 호출 시 항상 실패할거 같은데요.

`productId`가 없다면 요청을 보내기 전에 API 호출이 실행되지 않게 해보시는건 어떨까요?

2023-03-21 16:19 UTC, yujo11 commented on src/pages/ProductDetail.tsx
> +            onClick={() => onNavigateCartPage(product)}
`product`는 해당 컴포넌트에서 `useState`를 통해 관리되고 있는 값이기 때문에 컴포넌트 어디서든 하나의 `product`만 존재하는데요.

2023-03-21 16:19 UTC, yujo11 commented on src/pages/ProductDetail.tsx
> +  }
함수를 이렇게 변경한다면

```suggestion
  const onNavigateCartPage = async () => {
    await cartHttpClient?.addCart(product)
    navigate(NAVIGATE_URL.CARTS)
  }
```

2023-03-21 16:19 UTC, yujo11 commented on src/pages/ProductDetail.tsx
> +            onClick={() => onNavigateCartPage(product)}
익명함수를 사용지 않고 아래처럼 사용할 수 있을거 같아용
```suggestion
            onClick={onNavigateCartPage}
```

2023-03-21 16:19 UTC, yujo11 commented on src/pages/Products.tsx
> +  const [products, setProducts] = useState<ProductType[] | []>([])
코드를 보면서 생각난건데요

IDE에서 `error`나 `loading`에 마우스를 올려서 어떤 타입으로 추론되고 있는지 확인해보셔도 좋을거 같네요

2023-03-21 16:19 UTC, yujo11 commented on src/components/ui/Button/Button.tsx
> +      <span>{iconArea}</span>
`iconArea`를 prop으로 전달받지 못 하면 DOM에 아래처럼 빈 `<span>`태그만 남을거 같은데요.

조건부로 렌더해보시는건 어떨까요?

```html
<button>
   <span></span>
   text
</button>
```

2023-03-21 16:19 UTC, yujo11 commented on src/components/ui/Logo/Logo.tsx
`ui/` 폴더애 들어있지 않은 컴포넌트들도 `ui`를 같이 그려주고 있는거 같은데요.

`ui/`폴더 안에 있는 컴포넌트와 바깥에 있는 컴포넌트들은 어떤걸 기준으로 나누신걸까요?

2023-03-21 16:19 UTC, yujo11 commented on src/components/ui/Menu/Menu.tsx
> +}
여기에만 주석이 있는 이유가 있을까요?

2023-03-21 16:19 UTC, yujo11 commented on src/constants/menu.ts
> +]
`router`에 있는 `NAVIGATE_URL`을 이용하셔도 좋을거 같네용

2023-04-01 10:49 UTC, sooooo-an commented on public/mockServiceWorker.js
이 파일은 msw를 로컬에서 실행하기 위해 필요한 파일이라서 유지해놨습니다..!

2023-04-01 10:52 UTC, sooooo-an commented on src/components/ui/Logo/Logo.tsx
ui 컴포넌트의 경우에는, 전체 feature에서 사용하는 컴포넌트들이고, 밖에 있는 컴포넌트는 피쳐에서만 사용되고 있는 컴포넌트 기준으로 나눴는데, 그 이유는 폴더구조를 변경할 때, ui 폴더를 전체적으로 빼내기 위함이였습니다

2023-04-01 10:53 UTC, sooooo-an commented on src/components/ui/Menu/Menu.tsx
> +}
주석을 추가하여 스토리북에서도 설명이 나오게 하기 위함이였습니다

2023-04-01 11:03 UTC, sooooo-an commented on src/pages/Orders.tsx
> +                <OrderProducts key={order.id} order={order} />
ㅎㅎ 아녕.. 없습니당 컴포넌트들이 태그에 종속되지 않게 만드려고 li로 사용하는 곳에서 감쌌는데, 이 부분은 제가 놓친부분인 것 같습니다😭

2023-04-01 13:56 UTC, sooooo-an commented on src/App.tsx
당황함을... 제거해보았습니당...

2023-04-04 05:41 UTC, yujo11 commented on src/App.tsx
아닙니다 필요에 따라서 잘 분리해주신거 같아요! 👍 👍 👍

2023-04-04 05:44 UTC, yujo11 requested changes
수경님 안녕하세요~

리뷰를 하려고 확인해보니 지난 리뷰 이후 코드가 변경된 내역을 확인할 수 없는데요.

혹시 작업하신 내용들이 push 되었는지 다시 한번 확인해주시면 감사하겠습니다 🙇‍♂️

2023-04-06 08:31 UTC, yujo11 approved these changes
안녕하세요 수경님~

이전 리뷰에서 코멘트로 남겨드린 부분들을 대부분 꼼꼼하게 반영해주신거 같아요 👍 👍 👍 

다음 step 진행하면서 적용하실려고 계획하신 부분들이 있으신거 같은데 다음 step 리뷰도 기다리고 있겠습니다!

고생 많으셨습니다~ 👍 👍 👍

2023-04-06 08:31 UTC, yujo11 commented on public/robots.txt
👍👍👍

2023-04-06 08:31 UTC, yujo11 commented on .gitignore
지난 리뷰 이후 어떤 변경사항이 있는지 커밋 단위로 보고 있는데요. 

"feat: add log file"라는 이름 만으로는 `.gitignore`에 `*.log`가 추가되었다는걸 알기가 어렵네요.

다른 커밋들도 커밋 메시지 만으로 어떤 변경사항이 있었을지 알기 어려운 것들이 있는데요. 커밋 메세지를 조금 더 자세히 적어보셔도 좋을거 같아요!

2023-04-06 08:31 UTC, merged